package edu.vub.ideAT.ui;

import com.intellij.openapi.fileEditor.FileDocumentManager;
import com.intellij.openapi.wm.ToolWindow;
import com.intellij.ui.content.Content;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import edu.vub.ideAT.REPL.ATREPLInput;
import edu.vub.ideAT.REPL.ATREPLOutput;
import edu.vub.ideAT.REPL.IntelliJIAT;
import edu.vub.ideAT.configuration.ATRunnerState;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * Created by flo on 03/10/2016.
 */
public class ATREPL extends JFrame {
    private String scriptPath;
    private ATRunnerState runnerState;
    private Content toolWindowContent;
    private ToolWindow toolWindow;
    private JPanel root;
    private JLabel consoleName;
    private JTextArea consoleContent;
    private JLabel quitLabel;
    private JLabel refreshLabel;
    private ATREPLOutput replOutput;
    private ATREPLInput replInput;
    private IntelliJIAT interpreter;

    public ATREPL(String scriptName, ATRunnerState runnerState, ToolWindow toolWindow) {
        super("");
        $$$setupUI$$$();
        consoleContent.setCaretPosition(0);
        consoleName.setText(scriptName);
        replOutput = new ATREPLOutput(consoleContent);
        replInput = new ATREPLInput(consoleContent, this);
        scriptPath = scriptName;
        this.runnerState = runnerState;
        this.toolWindow = toolWindow;
    }

    public JPanel getPanel() {
        return root;
    }

    public JTextArea getContent() {
        return consoleContent;
    }

    public ATREPLOutput getOuput() {
        return replOutput;
    }

    public ATREPLInput getInput() {
        return replInput;
    }

    public IntelliJIAT getInterpreter() {
        return interpreter;
    }

    public void setIntelliJIAT(IntelliJIAT intelliJIAT) {
        interpreter = intelliJIAT;
    }

    public void setToolWindowContent(Content content) {
        toolWindowContent = content;
    }

    private void refreshInterpreter() {
        FileDocumentManager.getInstance().saveAllDocuments();
        runnerState.startATREPL(this);
    }

    private void killInterpreter() {
        toolWindow.getContentManager().removeContent(toolWindowContent, true);
        interpreter.abort("", new Exception());
    }

    private void createUIComponents() {
        quitLabel = new JLabel();
        quitLabel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                quitLabel.setIcon(new ImageIcon(getClass().getResource("/edu/vub/ideAT/ui/grayscale_close.png")));
                try {
                    Thread.sleep(300);
                    quitLabel.setIcon(new ImageIcon(getClass().getResource("/edu/vub/ideAT/ui/close.png")));
                    killInterpreter();
                } catch (InterruptedException e1) {
                    e1.printStackTrace();
                }
            }
        });
        refreshLabel = new JLabel();
        refreshLabel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                refreshLabel.setIcon(new ImageIcon(getClass().getResource("/edu/vub/ideAT/ui/grayscale_refresh.png")));
                try {
                    Thread.sleep(300);
                    refreshLabel.setIcon(new ImageIcon(getClass().getResource("/edu/vub/ideAT/ui/refresh.png")));
                    refreshInterpreter();
                } catch (InterruptedException e1) {
                    e1.printStackTrace();
                }
            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        root = new JPanel();
        root.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JScrollPane scrollPane1 = new JScrollPane();
        root.add(scrollPane1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        consoleContent = new JTextArea();
        scrollPane1.setViewportView(consoleContent);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        root.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        consoleName = new JLabel();
        consoleName.setEnabled(true);
        consoleName.setText("test");
        panel1.add(consoleName, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(417, 16), null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        quitLabel.setIcon(new ImageIcon(getClass().getResource("/edu/vub/ideAT/ui/close.png")));
        quitLabel.setText("");
        panel2.add(quitLabel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, new Dimension(16, 16), new Dimension(16, 16), new Dimension(16, 16), 0, false));
        refreshLabel.setIcon(new ImageIcon(getClass().getResource("/edu/vub/ideAT/ui/refresh.png")));
        refreshLabel.setText("");
        panel2.add(refreshLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, new Dimension(16, 16), new Dimension(16, 16), new Dimension(16, 16), 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }
}
